config/routes.rb
BoothControl::Application.routes.draw do
  resources :maps

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }

  match 'reserved_booths' => 'pages#reserved_booths'
  
  match 'welcome' => 'pages#welcome', :as => 'user_root'
  match 'export' => 'pages#export'
  match 'exportable' => 'pages#exportable'

  resources :colors
  resources :exhibitor_types
  resources :booths
  resources :states
  resources :countries
  resources :companies do
    resources :reservations, :contacts, :offices
  end
  

  root :to => "pages#home"

end

app/models/booth.rb
class Booth < ActiveRecord::Base
  attr_accessible :code, :color_id, :booth_number, :available
  validates_presence_of :code, :color_id, :booth_number
  validates_uniqueness_of :code, :booth_number
  
  belongs_to :color
  delegate :hex_value, :to => :color, :prefix => true
  
  has_one :reservation, :dependent => :destroy
  has_one :company, :through => :reservation
  delegate :name, :profile, :to => :company, :prefix => true
  
  scope :free, where(:available => true)
  scope :reserved, where(:available => false)
  
  def color_name
    color.name if color
  end
  
  def color_name=(name)
    self.color = Color.find_by_name(name) unless name.blank?
  end
  
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :name, :hex_value
  validates_presence_of :name, :hex_value
  validates_uniqueness_of :hex_value, :name
  
  has_many :booths
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :profile, :exhibitor_type_id, :user_id
  
  validates_presence_of :name, :profile, :exhibitor_type_id
  validates_uniqueness_of :name
  validates_length_of :profile, :maximum => 420
  
  belongs_to :user
  delegate :name, :to => :user, :prefix => true
  belongs_to :exhibitor_type
  delegate :name, :to => :exhibitor_type, :prefix => true
  
  has_many :reservations, :dependent => :destroy
  has_many :booths, :through => :reservations
  has_one :contact, :dependent => :destroy
  has_one :office, :dependent => :destroy
  
  
  def booth_export
    company_booths = []
    self.reservations.each do |r|
      company_booths << r.booth.booth_number
    end
    company_booths
  end
  
  def to_s
    company_booths = []
    self.reservations.each do |r|
      company_booths << r.booth.booth_number
    end
    company_booths.join(', ').to_s
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :email, :company_id
  validates_presence_of :name, :email
  belongs_to :company
  
  EmailRegex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :email, :with => EmailRegex
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :offices
  
  scope :ordered, order("name asc")
end

app/models/exhibitor_type.rb
class ExhibitorType < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :companies
end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :map_file, :zoom, :zoom_x, :zoom_y
  validates_presence_of :map_file, :zoom, :zoom_x, :zoom_y
end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :state_id, :zip, :country_id, :rfc, :phone, :fax, :website, :company_id, :state_name, :country_name, :taxname
  
  validates_presence_of :address1, :city, :state_id, :country_id, :company_id, :state_name, :country_name, :taxname
  validates_uniqueness_of :rfc, :allow_nil => true
  validates_uniqueness_of :taxname
  
  belongs_to :company
  belongs_to :state
  delegate :name, :to => :state, :prefix => true
  belongs_to :country
  delegate :name, :to => :country, :prefix => true
  
  def state_name
    state.name if state
  end
  
  def state_name=(name)
    self.state = State.find_or_create_by_name(name) unless name.blank?
  end
  
  def country_name
    country.name if country
  end
  
  def country_name=(name)
    self.country = Country.find_or_create_by_name(name) unless name.blank?
  end
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :booth_id, :company_id, :booth_number
  
  validates_presence_of :booth_id, :company_id
  validates_uniqueness_of :booth_id
  
  belongs_to :booth
  belongs_to :company
  
  def booth_number
    booth.booth_number if booth
  end
  
  def booth_number=(booth_number)
    self.booth = Booth.find_by_booth_number(booth_number) unless booth_number.blank?
  end
  
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :offices
  
  scope :ordered, order("name asc")
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  
  has_many :companies
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :find_map, :only => [:show, :edit, :update]
  # GET /maps
  # GET /maps.xml
  def index
    @maps = Map.all
    if Map.count > 0
      @map = Map.first
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.xml
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.xml
  def create
    @map = Map.new(params[:map])

    respond_to do |format|
      if @map.save
        format.html { redirect_to(maps_path, :notice => 'Mapa configurado.') }
        format.xml  { render :xml => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.xml
  def update

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to(maps_path, :notice => 'Mapa configurado.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  private
  
  def find_map
    @map = Map.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booths_helper.rb
module BoothsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :map_file %><br />
    <%= f.text_field :map_file %>
  </div>
  <div class="field">
    <%= f.label :zoom %><br />
    <%= f.text_field :zoom %>
  </div>
  <div class="field">
    <%= f.label :zoom_x %><br />
    <%= f.text_field :zoom_x %>
  </div>
  <div class="field">
    <%= f.label :zoom_y %><br />
    <%= f.text_field :zoom_y %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'as_button' %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h2>Configurar mapa</h2>

<%= render 'form' %>

<%= link_to 'Regresar', maps_path %>

app/views/maps/index.html.erb
<h2>Configuraci&oacute;n de mapa</h2>


<% @maps.each do |map| %>
    Archivo de mapa: <%= map.map_file %><br />
    Valor de Zoom: <%= map.zoom %><br />
    Zoom_x: <%= map.zoom_x %><br />
    Zoom_y: <%= map.zoom_y %><br />
<% end %>


<br />
<% if Map.count == 0 %>
	<%= link_to "<span class=\"ui-icon ui-icon-gear\" style=\"float: left; margin-right: 5px;\">icon</span>Configurar mapa".html_safe, new_map_path, :class => 'as_button' %>
<% else %>
	<%= link_to "<span class=\"ui-icon ui-icon-gear\" style=\"float: left; margin-right: 5px;\">icon</span>Configurar mapa".html_safe, edit_map_path(@map), :class => 'as_button' %>
<% end %>

app/views/maps/new.html.erb
<h2>Configurar mapa</h2>

<%= render 'form' %>

<%= link_to 'Regresar', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Map file:</b>
  <%= @map.map_file %>
</p>

<p>
  <b>Zoom:</b>
  <%= @map.zoom %>
</p>

<p>
  <b>Zoom x:</b>
  <%= @map.zoom_x %>
</p>

<p>
  <b>Zoom y:</b>
  <%= @map.zoom_y %>
</p>


<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>