config/routes.rb
BoothControl::Application.routes.draw do
  resources :maps

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }

  match 'reserved_booths' => 'pages#reserved_booths'
  
  match 'welcome' => 'pages#welcome', :as => 'user_root'
  match 'export' => 'pages#export'
  match 'exportable' => 'pages#exportable'

  resources :colors
  resources :exhibitor_types
  resources :booths
  resources :states
  resources :countries
  resources :companies do
    resources :reservations, :contacts, :offices
  end
  

  root :to => "pages#home"

end

app/models/booth.rb
class Booth < ActiveRecord::Base
  attr_accessible :code, :color_id, :booth_number, :available
  validates_presence_of :code, :color_id, :booth_number
  validates_uniqueness_of :code, :booth_number
  
  belongs_to :color
  delegate :hex_value, :to => :color, :prefix => true
  
  has_one :reservation, :dependent => :destroy
  has_one :company, :through => :reservation
  delegate :name, :profile, :to => :company, :prefix => true
  
  scope :free, where(:available => true)
  scope :reserved, where(:available => false)
  
  def color_name
    color.name if color
  end
  
  def color_name=(name)
    self.color = Color.find_by_name(name) unless name.blank?
  end
  
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :name, :hex_value
  validates_presence_of :name, :hex_value
  validates_uniqueness_of :hex_value, :name
  
  has_many :booths
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :profile, :exhibitor_type_id, :user_id
  
  validates_presence_of :name, :profile, :exhibitor_type_id
  validates_uniqueness_of :name
  validates_length_of :profile, :maximum => 420
  
  belongs_to :user
  delegate :name, :to => :user, :prefix => true
  belongs_to :exhibitor_type
  delegate :name, :to => :exhibitor_type, :prefix => true
  
  has_many :reservations, :dependent => :destroy
  has_many :booths, :through => :reservations
  has_one :contact, :dependent => :destroy
  has_one :office, :dependent => :destroy
  
  
  def booth_export
    company_booths = []
    self.reservations.each do |r|
      company_booths << r.booth.booth_number
    end
    company_booths
  end
  
  def to_s
    company_booths = []
    self.reservations.each do |r|
      company_booths << r.booth.booth_number
    end
    company_booths.join(', ').to_s
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :email, :company_id
  validates_presence_of :name, :email
  belongs_to :company
  
  EmailRegex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :email, :with => EmailRegex
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :offices
  
  scope :ordered, order("name asc")
end

app/models/exhibitor_type.rb
class ExhibitorType < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :companies
end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :map_file, :zoom, :zoom_x, :zoom_y
  validates_presence_of :map_file, :zoom, :zoom_x, :zoom_y
end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :state_id, :zip, :country_id, :rfc, :phone, :fax, :website, :company_id, :state_name, :country_name, :taxname
  
  validates_presence_of :address1, :city, :state_id, :country_id, :company_id, :state_name, :country_name, :taxname
  validates_uniqueness_of :rfc, :allow_nil => true
  validates_uniqueness_of :taxname
  
  belongs_to :company
  belongs_to :state
  delegate :name, :to => :state, :prefix => true
  belongs_to :country
  delegate :name, :to => :country, :prefix => true
  
  def state_name
    state.name if state
  end
  
  def state_name=(name)
    self.state = State.find_or_create_by_name(name) unless name.blank?
  end
  
  def country_name
    country.name if country
  end
  
  def country_name=(name)
    self.country = Country.find_or_create_by_name(name) unless name.blank?
  end
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :booth_id, :company_id, :booth_number
  
  validates_presence_of :booth_id, :company_id
  validates_uniqueness_of :booth_id
  
  belongs_to :booth
  belongs_to :company
  
  def booth_number
    booth.booth_number if booth
  end
  
  def booth_number=(booth_number)
    self.booth = Booth.find_by_booth_number(booth_number) unless booth_number.blank?
  end
  
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :offices
  
  scope :ordered, order("name asc")
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  
  has_many :companies
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  before_filter :find_company, :only => [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  def index
    @companies = Company.order("name asc")
  end
  
  def show
  end
  
  def new
    #@company = Company.new
    @company = current_user.companies.build
  end
  
  def create
    #@company = Company.new(params[:company])
    @company = current_user.companies.build(params[:company])
    if @company.save
      flash[:notice] = "Nueva Empresa agregado"
      redirect_to new_company_contact_path(@company)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @company.update_attributes(params[:company])
      flash[:notice] = 'Empresa modificada'
      redirect_to @company
    else
      render 'edit'
    end
  end
  
  def destroy
    @company.reservations.each do |reservation|
      reservation.booth.update_attribute(:available, true)
    end
    @company.destroy
    flash[:notice] = 'Empresa eliminada'
    redirect_to companies_path
  end
  
  private
  
  def find_company
    @company = Company.find(params[:id])
  end
  
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :find_map, :only => [:show, :edit, :update]
  # GET /maps
  # GET /maps.xml
  def index
    @maps = Map.all
    if Map.count > 0
      @map = Map.first
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.xml
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.xml
  def create
    @map = Map.new(params[:map])

    respond_to do |format|
      if @map.save
        format.html { redirect_to(maps_path, :notice => 'Mapa configurado.') }
        format.xml  { render :xml => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.xml
  def update

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to(maps_path, :notice => 'Mapa configurado.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  private
  
  def find_map
    @map = Map.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booths_helper.rb
module BoothsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/companies/_form.html.erb
<%= semantic_form_for company do |f| %>
	<% if company.errors.any? %>
		<div id="error_explanation" class="ui-widget alert">
			<div class="ui-state-error ui-corner-all">
				<h2><%= pluralize(company.errors.count, "error") %>: Por favor corregir</h2>
				<ul>
					<% company.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		</div>
	<% end %>
	<p>
		<%= f.label "Nombre" %><br />
		<%= f.text_field :name, :required => true %>
	</p>
	<p>
		<%= f.label "Perfil" %><br />
		<%= f.input :profile, :as => :text, :label => false, :required => true %>
	</p>
	<p>
		<%= f.label "Tipo de Expositor " %>
		<%= f.input :exhibitor_type, :as => :select, :label => false, :prompt => "Seleccione...", :required => true  %>
	</p>
	<p><%= f.submit "Listo", :class => 'as_button' %></p>
<% end %>

app/views/companies/edit.html.erb
<h2>Editar expositor</h2>

<%= render :partial => 'form', :locals => { :company => @company } %>

app/views/companies/index.html.erb
<div>
	<div class="grid_12 alpha">
		<h2>Expositores</h2>
	</div>
	<div class="grid_4 alpha">
		<%= link_to "<span class=\"ui-icon ui-icon-circle-plus\" style=\"float: left; margin-right: 5px;\">icon</span>Nuevo Expositor".html_safe, new_company_path, :class => 'as_button' %>
	</div>
</div>
<table id="expositores">
	<thead>
		<tr>
			<th>Agente</th>
			<th>Expositor</th>
			<th>Booths</th>
			<th>Tipo</th>
			<th>Agregado en</th>
		</tr>
	</thead>
	<tbody>
		<% @companies.each do |company| %>
			<tr>
				<td class="quarters"><%= company.user_name %></td>
				<td class="quarters">
					<p><%= link_to company.name, company %></p>
				</td>
				<td class="quarters">
					<% company_booths = []
						company.booths.each do |booth|
							company_booths << booth.booth_number
						end
					 %>
					<p><%= company_booths.join(', ') %></p>
				</td>
				<td class="quarters"><%= company.exhibitor_type_name %></td>
				<td class="quarters"><%= l company.created_at, :format => :custom %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/companies/new.html.erb
<h2>Agregar expositor</h2>

<%= render :partial => 'form', :locals => { :company => @company } %>

app/views/companies/show.html.erb
<div class="grid_12 alpha">
	<div id="company-info">
		<div class="grid_8 alpha">
			<h2><%= @company.name %></h2>
			<p><%= @company.profile %></p>
			<p>Tipo de Expositor: <%= @company.exhibitor_type_name %></p>
			<p>Agente: <%= @company.user_name %></p>
		</div>
		<div class="grid_4 omega">
			<%= link_to "<span class=\"ui-icon ui-icon-pencil\" style=\"float: left;\">icon</span> Editar".html_safe, edit_company_path(@company), :class => 'as_button' %> <%= link_to "<span class=\"ui-icon ui-icon-trash\" style=\"float: left;\">icon</span> Borrar".html_safe, company_path(@company), :method => :delete, :class => 'as_button' %>
		</div>
	</div>
	<hr />
	<div id="contact-info">
		<% if @company.contact %>
			<div>
				<div class="grid_8 alpha">
					<h3>Contacto</h3>
					<%= @company.contact.name %><br />
					<%= @company.contact.email %>
				</div>
				<div class="grid_4 omega">
					<%= link_to "<span class=\"ui-icon ui-icon-pencil\" style=\"float: left;\">icon</span> Editar".html_safe, edit_company_contact_path(@company, @company.contact), :class => 'as_button' %> <%= link_to "<span class=\"ui-icon ui-icon-trash\" style=\"float: left;\">icon</span> Borrar".html_safe, company_contact_path(@company, @company.contact), :method => :delete, :class => 'as_button' %>
				</div>
			</div>
		<% else %>
		<h3>Contacto</h3>
		<%= link_to "<span class=\"ui-icon ui-icon-circle-plus\" style=\"float: left; margin-right: 5px;\">icon</span>Agregar contacto".html_safe, new_company_contact_path(@company), :class => 'as_button' %>
		<% end %>
		<hr />
	</div>
	<div id="office-info">
		<% if @company.office %>
			<div>
				<div class="grid_8 alpha">
					<h3>Direcci&oacute;n</h3>
					<% office = @company.office %>
					<% line1 = [office.address1, office.address2] %>
					<% line2 = [office.city, office.state_name, office.zip] %>
					<%= office.taxname %><br />
					<%= line1.join(', ')%><br />
					<%= line2.join(', ') %><br />
					<%= office.country_name unless office.country.nil? %><br />
					Tel. <%= office.phone unless office.phone.blank? %><br />
					Fax <%= office.fax unless office.fax.blank? %><br />
					Website: <%= office.website unless office.website.blank? %><br />
					<%= "RFC: " + office.rfc unless office.rfc.blank? %>
				</div>
				<div class="grid_4 omega">
					<%= link_to "<span class=\"ui-icon ui-icon-pencil\" style=\"float: left;\">icon</span> Editar".html_safe, edit_company_office_path(@company, @company.office), :class => 'as_button' %> <%= link_to "<span class=\"ui-icon ui-icon-trash\" style=\"float: left;\">icon</span> Borrar".html_safe, company_office_path(@company, @company.office), :method => :delete, :class => 'as_button' %>
				</div>
			</div>
		<% else %>
		<h3>Direcci&oacute;n</h3>
		<%= link_to "<span class=\"ui-icon ui-icon-circle-plus\" style=\"float: left; margin-right: 5px;\">icon</span>Agregar direcci&oacute;n".html_safe, new_company_office_path(@company), :class => 'as_button' %>
		<% end %>
	</div>
	<div class="clear"></div>
	<p class="back"><%= link_to "<span class=\"ui-icon ui-icon-arrow-1-w\" style=\"float: left;\">icon</span> Regresar".html_safe, companies_path, :class => 'as_button' %></p>
</div>
<div class="grid_4 omega">
	<h3>Booths asignados</h3>
	<ul>
		<% @company.reservations.each do |reservation| %>
			<li class="booths">
				<div class="sample" style="background: #<%= reservation.booth.color_hex_value %>">
					<span>&nbsp;</span>
				</div>
				<div class="stack">
					<%= reservation.booth.booth_number %>
				</div>
				<div class="stack">
					<%= link_to "<span class=\"ui-icon ui-icon-trash\" style=\"float: left; margin-right: 5px;\">icon</span>".html_safe, company_reservation_path(@company, reservation), :confirm => "Esta seguro que desea borrar esta Reservacion?", :method => :delete %>
				</div>
				<div class="clear"></div>
			</li>
		<% end %>
	</ul>
	<p><%= link_to "<span class=\"ui-icon ui-icon-circle-plus\" style=\"float: left; margin-right: 5px;\">icon</span>Agregar booth".html_safe, new_company_reservation_path(@company), :class => 'as_button' %></p>
</div>
<div class="clear"></div>