config/routes.rb
BoothControl::Application.routes.draw do
  resources :maps

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }

  match 'reserved_booths' => 'pages#reserved_booths'
  
  match 'welcome' => 'pages#welcome', :as => 'user_root'
  match 'export' => 'pages#export'
  match 'exportable' => 'pages#exportable'

  resources :colors
  resources :exhibitor_types
  resources :booths
  resources :states
  resources :countries
  resources :companies do
    resources :reservations, :contacts, :offices
  end
  

  root :to => "pages#home"

end

app/models/booth.rb
class Booth < ActiveRecord::Base
  attr_accessible :code, :color_id, :booth_number, :available
  validates_presence_of :code, :color_id, :booth_number
  validates_uniqueness_of :code, :booth_number
  
  belongs_to :color
  delegate :hex_value, :to => :color, :prefix => true
  
  has_one :reservation, :dependent => :destroy
  has_one :company, :through => :reservation
  delegate :name, :profile, :to => :company, :prefix => true
  
  scope :free, where(:available => true)
  scope :reserved, where(:available => false)
  
  def color_name
    color.name if color
  end
  
  def color_name=(name)
    self.color = Color.find_by_name(name) unless name.blank?
  end
  
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :name, :hex_value
  validates_presence_of :name, :hex_value
  validates_uniqueness_of :hex_value, :name
  
  has_many :booths
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :profile, :exhibitor_type_id, :user_id
  
  validates_presence_of :name, :profile, :exhibitor_type_id
  validates_uniqueness_of :name
  validates_length_of :profile, :maximum => 420
  
  belongs_to :user
  delegate :name, :to => :user, :prefix => true
  belongs_to :exhibitor_type
  delegate :name, :to => :exhibitor_type, :prefix => true
  
  has_many :reservations, :dependent => :destroy
  has_many :booths, :through => :reservations
  has_one :contact, :dependent => :destroy
  has_one :office, :dependent => :destroy
  
  
  def booth_export
    company_booths = []
    self.reservations.each do |r|
      company_booths << r.booth.booth_number
    end
    company_booths
  end
  
  def to_s
    company_booths = []
    self.reservations.each do |r|
      company_booths << r.booth.booth_number
    end
    company_booths.join(', ').to_s
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :email, :company_id
  validates_presence_of :name, :email
  belongs_to :company
  
  EmailRegex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :email, :with => EmailRegex
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :offices
  
  scope :ordered, order("name asc")
end

app/models/exhibitor_type.rb
class ExhibitorType < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :companies
end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :map_file, :zoom, :zoom_x, :zoom_y
  validates_presence_of :map_file, :zoom, :zoom_x, :zoom_y
end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :state_id, :zip, :country_id, :rfc, :phone, :fax, :website, :company_id, :state_name, :country_name, :taxname
  
  validates_presence_of :address1, :city, :state_id, :country_id, :company_id, :state_name, :country_name, :taxname
  validates_uniqueness_of :rfc, :allow_nil => true
  validates_uniqueness_of :taxname
  
  belongs_to :company
  belongs_to :state
  delegate :name, :to => :state, :prefix => true
  belongs_to :country
  delegate :name, :to => :country, :prefix => true
  
  def state_name
    state.name if state
  end
  
  def state_name=(name)
    self.state = State.find_or_create_by_name(name) unless name.blank?
  end
  
  def country_name
    country.name if country
  end
  
  def country_name=(name)
    self.country = Country.find_or_create_by_name(name) unless name.blank?
  end
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :booth_id, :company_id, :booth_number
  
  validates_presence_of :booth_id, :company_id
  validates_uniqueness_of :booth_id
  
  belongs_to :booth
  belongs_to :company
  
  def booth_number
    booth.booth_number if booth
  end
  
  def booth_number=(booth_number)
    self.booth = Booth.find_by_booth_number(booth_number) unless booth_number.blank?
  end
  
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :offices
  
  scope :ordered, order("name asc")
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  
  has_many :companies
end

app/helpers/booths_helper.rb
module BoothsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/_header.html.erb
<div id="navigation">
	<% if user_signed_in? %>
			<div id="login-info">
				Loggeado como <%= current_user.name %>. &iquest;No eres t&uacute;? <%= link_to "Salir", destroy_user_session_path %>
			</div>
			<div class="clear"></div>
			<div id="menu" class="menu">
				<ul id="nav" class="dropdown dropdown-horizontal">
					<li id="dashboard"><%= link_to "Dashboard", user_root_path %></li>
					<li id="new-company"><%= link_to "Agregar expositor", new_company_path %></li>
					<li id="companies"><%= link_to "Lista de expositores", companies_path %></li>
					<li id="config"><span class="dir">Configuraci&oacute;n</span>
						<% if current_user.admin? %>
						<ul>
							<li class="first"><%= link_to "Colores", colors_path %></li>
							<li><%= link_to "Booths", booths_path %></li>
							<li><%= link_to "Tipos de expositores", exhibitor_types_path %></li>
							<li><%= link_to "Configurar mapa", maps_path %></li>
							<li><%= link_to "Exportar datos", exportable_path %></li>
						</ul>
						<% end %>
					</li>
				</ul>
			</div>
			<div class="clear"></div>
	<% end %>
</div>
<div class="clear"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoothControl</title>
  <%= stylesheet_link_tag '960', 'text', 'reset', 'jquery-ui-twitter' %>
  <%= stylesheet_link_tag 'demo_page', 'demo_table', 'demo_table_jui', 'TableTools', 'application', 'uniform.aristo' %>
  <%= stylesheet_link_tag 'dropdown', 'default.ultimate' %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="wrapper" class="container_16">
		<div id="page" class="grid_16">
			<div id="header">
				<%= render :partial => 'layouts/header' %>
			</div>
			<div class="clear"></div>
			<div id="content">
				<% if notice %>
				<div class="ui-widget notice">
					<div class="ui-state-highlight ui-corner-all">
						<span style="float: left; margin-right: 0.3em; margin-top: 0.3em" class="ui-icon ui-icon-info">icon</span>
						<%= notice %>
					</div>
				</div>
				<% end %>
				<% if alert %>
				<div class="ui-widget alert">
					<div class="ui-state-error ui-corner-all">
						<span style="float: left; margin-right: 0.3em; margin-top: 0.45em" class="ui-icon ui-icon-info">icon</span>
						<%= alert %>
					</div>
				</div>
				<% end %>
				<%= yield %>
			</div>
			<div class="clear"></div>
			<div id="footer">
				<%= javascript_include_tag 'jquery', 'rails' %>
				<%= javascript_include_tag 'jquery-ui', 'jquery.dataTables', 'TableTools.min', 'ZeroClipboard', 'jquery.uniform.min', 'jquery.validate.min', 'messages_es', 'jquery.counter.min', 'application' %>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</body>
</html>